services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest 
    environment:
      - MSSQL_SA_PASSWORD=${SQL_SA_PASSWORD}
  
  redis:
    image: redis:7.4

  rabbitmq:
    image: rabbitmq:3-management 

  keycloak:
    networks:
      default:
        aliases:
          - localhost
    ports:
        - "8081:8080"
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN_USER}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_HOSTNAME=${KC_HOSTNAME}
      - KC_HTTP_RELATIVE_PATH=${KC_HTTP_RELATIVE_PATH}
      - KC_PROXY_HEADERS=xforwarded
      - KC_HOSTNAME_STRICT=${KC_HOSTNAME_STRICT}
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME_STRICT_HTTPS=${KC_HOSTNAME_STRICT_HTTPS}
      
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./tienda-realm-export.json:/opt/keycloak/data/import/realm.json:ro

  gateway-nginx:
    image: nginx:alpine
    ports:
      - "80:80" 
    networks:
      default:
        aliases:
          - localhost
    volumes:
      - ./TiendaAspire.admin-dashBoard/nginx.localalias.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - admin-dashboard
      - tienda-web
  
  inventario-api:
    extra_hosts:
      - ${HOSTNAME}:host-gateway
 
  catalogo-api:
     extra_hosts:
      - ${HOSTNAME}:host-gateway

  admin-dashboard: 
    build:
      args:
        - BASE_HREF=/admin/
        - CONFIGURATION=development
    environment:
      - KEYCLOAK_URL=${KEYCLOAK_URL}
    