apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: rabbit-pubsub
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
  - name: connectionString
    value: amqp://guest:guest@rabbitmq:5672
  - name: backOffMaxRetries
    value: "15"              # Allow up to 15 retries
  - name: backOffInitialInterval
    value: "2000"            # Wait 2 seconds before the first retry (instead of milliseconds)
  - name: backOffMaxInterval
    value: "5000"
  - name: ignoreErrors
    value: "true"	
scopes:
  - inventarioservice
  - catalogoservice
